package hr.kiki.leads.entity;
// Generated May 1, 2019 6:00:00 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CarPropertyId generated by hbm2java
 */
@Embeddable
public class CarPropertyId  implements java.io.Serializable {


     private BigDecimal carId;
     private BigDecimal propId;
     private String value;

    public CarPropertyId() {
    }

	
    public CarPropertyId(BigDecimal carId, BigDecimal propId) {
        this.carId = carId;
        this.propId = propId;
    }
    public CarPropertyId(BigDecimal carId, BigDecimal propId, String value) {
       this.carId = carId;
       this.propId = propId;
       this.value = value;
    }
   

    @Column(name="car_id", nullable=false, precision=131089, scale=0)
    public BigDecimal getCarId() {
        return this.carId;
    }
    
    public void setCarId(BigDecimal carId) {
        this.carId = carId;
    }

    @Column(name="prop_id", nullable=false, precision=131089, scale=0)
    public BigDecimal getPropId() {
        return this.propId;
    }
    
    public void setPropId(BigDecimal propId) {
        this.propId = propId;
    }

    @Column(name="value")
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CarPropertyId) ) return false;
		 CarPropertyId castOther = ( CarPropertyId ) other; 
         
		 return ( (this.getCarId()==castOther.getCarId()) || ( this.getCarId()!=null && castOther.getCarId()!=null && this.getCarId().equals(castOther.getCarId()) ) )
 && ( (this.getPropId()==castOther.getPropId()) || ( this.getPropId()!=null && castOther.getPropId()!=null && this.getPropId().equals(castOther.getPropId()) ) )
 && ( (this.getValue()==castOther.getValue()) || ( this.getValue()!=null && castOther.getValue()!=null && this.getValue().equals(castOther.getValue()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCarId() == null ? 0 : this.getCarId().hashCode() );
         result = 37 * result + ( getPropId() == null ? 0 : this.getPropId().hashCode() );
         result = 37 * result + ( getValue() == null ? 0 : this.getValue().hashCode() );
         return result;
   }   


}


