CREATE TABLE LEAD (
                ID NUMERIC NOT NULL,
                CUS_ID NUMERIC NOT NULL,
                NOTES VARCHAR ,
                CONSTRAINT PK_LEAD PRIMARY KEY (ID)
);

CREATE TABLE CUSTOMER (
                ID NUMERIC NOT NULL,
                EXT_ID VARCHAR ,
                NAME VARCHAR ,
                EMAIL VARCHAR,
                PHONE VARCHAR,
                CONSTRAINT PK_CUSTOMER PRIMARY KEY (ID)
);

CREATE TABLE CAR (
                ID NUMERIC NOT NULL,
                BRAND VARCHAR ,
                MODEL VARCHAR ,
                CONSTRAINT PK_CAR PRIMARY KEY (ID)
);


CREATE TABLE LEAD_CAR (
                LEAD_ID NUMERIC NOT NULL,
                CAR_ID NUMERIC NOT null,
                CONSTRAINT lead_car_U UNIQUE (LEAD_ID, CAR_ID)
);



CREATE TABLE CAR_PROPERTY (
                CAR_ID NUMERIC NOT NULL,
                PROP_ID NUMERIC NOT NULL,
                VALUE VARCHAR --,
                CONSTRAINT car_prop_U UNIQUE (PROP_ID, CAR_ID)
);


CREATE TABLE PROPERTY (
                ID NUMERIC NOT NULL,
                NAME VARCHAR,
                CONSTRAINT PROPERTY_pk PRIMARY KEY (ID)
);

-- KREIRANJE STRANIH KLJUČEVA ODVOJENO, KAKO BI SE KOD MIGRACIJE PODATAKA TABLICE MOGLE NEOVISNO PUNITI,
-- A TEK ZATIM KREIRATI KLJUČEVI.



ALTER TABLE LEAD ADD CONSTRAINT LEAD_CUSTOMER_FK
FOREIGN KEY (CUS_ID)
REFERENCES CUSTOMER (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE LEAD_CAR ADD CONSTRAINT LEAD_CAR_LEAD_FK
FOREIGN KEY (LEAD_ID)
REFERENCES LEAD (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE LEAD_CAR ADD CONSTRAINT LEAD_CAR_CAR_FK
FOREIGN KEY (CAR_ID)
REFERENCES CAR (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE CAR_PROPERTY ADD CONSTRAINT CAR_PROPERTY_CAR_FK
FOREIGN KEY (CAR_ID)
REFERENCES CAR (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE CAR_PROPERTY ADD CONSTRAINT CAR_PROPERTY_PROPERTY_FK
FOREIGN KEY (PROP_ID)
REFERENCES PROPERTY (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

CREATE SEQUENCE LEAD_SEQ;
CREATE SEQUENCE CAR_SEQ;
CREATE SEQUENCE CUSTOMER_SEQ;
CREATE SEQUENCE PROPERTY_SEQ;



